FROM ubuntu:latest
LABEL "Author" = "Aditya"
LABEL "Project" = "new-spot"
ENV DEBIAN_FRONTEND = noninteractive
RUN apt update && apt install git -y
RUN apt install apache2 -y
CMD ["/usr/sbin/apache2ctl","-D","FOREGROUND"]
EXPOSE 80
WORKDIR /var/www/html
VOLUME /var/log/apache2
ADD new-spot.tar.gz /var/www/html











docker run --name myweb -p 9080:80 -d bhangiri/new
